

INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best', '33', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Refractors', '33', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Atomic Refractors', '33', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Cuts', 'BC3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Cuts', 'BC3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Cuts Refractors', 'BC3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Cuts Atomic Refractors', 'BC3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Cuts Atomic Refractors', 'BC3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Retro', 'TB20', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Retro Refractors', 'TB20', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Retro Atomic Refractors', 'TB20', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Honor Roll G.Hill/J.Howard', 'HR9', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Honor Roll Refractors G.Hill/J.Howard', 'HR9', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Honor Roll Refractors G.Hill/J.Howard', 'HR9', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Bowman\'s Best Honor Roll Atomic Refractors G.Hill/J.Howard', 'HR9', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice', '352', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Crash the Game Scoring 2', 'C29', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Crash the Game Scoring 2 Gold', 'C29', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Crash the Game Scoring 2', 'C29B', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Crash the Game Scoring 2 Gold', 'C29B', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Crash the Game Scoring 2 Silver Redemption', 'R29', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Crash the Game Scoring 2 Gold Redemption', 'R29', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Mini Cards', 'M178', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Mini Cards Gold', 'M178', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Collector\'s Choice Stick-Ums 2', 'S29', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'E-X2000', '79', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'E-X2000 Credentials', '79', '#259/399');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'E-X2000 Star Date 2000', '6', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest', '85 B', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest Refractors', '85 B', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest', '140 G', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest Refractors', '140 G', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest', '261 S', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest', '261 S', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Finest Refractors', '261 S', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Hot Shots', '10', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Row 0', '5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Row 1', '5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Row 2', '5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Legacy Collection Row 0', '5', '#011/150');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Legacy Collection Row 1', '5', '#013/150');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Flair Showcase Legacy Collection Row 2', '5', '#022/150');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Fleer', '116', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Fleer Hardwood Leaders', '148', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Fleer All Stars', '297', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Fleer Franchise Futures', '4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Fleer Total O', '3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Hoops', '170', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Hoops', '333 CBG', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Hoops Fly With', '2', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Hoops HIPnotized', 'H20', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Hoops Starting Five /Bullets', '29', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal', '106', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal', '240 MS', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal Precious Metal', '240 MS', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal Maximum Metal', '11', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal Molten Metal', '5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal Net-Rageous', '4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Metal Power Tools', '4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium', '127', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Rubies', '127', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium', '245', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Rubies', '245', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Autographics', '30', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Autographics Blue', '30', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Close-Ups', 'CU3', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Net Set', '6', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SkyBox Premium Thunder and Lightning J.Howard/C.Webber', '10', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SP', '123', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SP Holoviews', 'PC40', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'SP SPx Force Kemp/Rod/Barkley/Juwan', 'F2', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club', '98', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Stadium Club Class Acts C.Webber/J.Howard', 'CA4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Class Act Refractors C.Webber/J.Howard', 'CA4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Class Act Atomic Refractors C.Webber/J.Howard', 'CA4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Fusion', 'F18', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Fusion Members Only', 'F18', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Fusion Uncut', 'F18', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club High Risers', 'HR15', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club High Risers Members Only', 'HR15', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Top Crop J.Howard/C.Barkley', 'TC7', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Members Only 55', '45', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Stadium Club Members Only 55', '45', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps', '137', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Chrome', '137', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Chrome Refractor', '137R', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Chrome Pro Files', 'PF12', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Mystery Finest Bordered', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Mystery Finest Borderless', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Mystery Finest Bordered Refractor', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Mystery Finest Borderless Refractor', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Super Team Conference Winners Bordered', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Super Team Conference Winners Borderless', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Super Team Conference Winners Borderless', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Super Team Conference Winners Bordered Refractor', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Super Team Conference Winners Bordered Refractor', 'M5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps NBA at 50', '137', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Topps Pro Files', 'PF12', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'UD3', '37', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'UD3 The Winning Edge', 'W11', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra', '121', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra Gold Medallion', 'G121', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra Platinum Medallion', 'P121', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra OTB', '127', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra OTB', '127', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra OTB Gold Medallion', '127', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra OTB Platinum Medallion', 'P127', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra Court Masters', '12', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra Rising Stars', '5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Ultra Rising Stars Error', '5', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Upper Deck Howard/Muresan/Web BW', '164', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Upper Deck', '312', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Upper Deck Predictor Scoring 2', 'P20', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Upper Deck Predictor TV Cel Redemption 2', 'TV20', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Z-Force', '95', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Z-Force ZUP', '176', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Z-Force Vortex', 'V4', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1996-97', 'Z-Force Z-Cling', '95', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1997', 'SPx', '50', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1997', 'SPx Gold', '50', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1997', 'SPx Holoview Heroes', 'H12', '--');
INSERT INTO tableName (season, card_brand, number, print_run) VALUES ('1997', 'Upper Deck Slam Dunk', 'SD15', '--');
