package de.maulmann.cardcollection.repository

import de.maulmann.cardcollection.model.Card
import de.maulmann.cardcollection.model.Player
import de.maulmann.cardcollection.model.Variant
import de.maulmann.cardcollection.model.CardTheme
import de.maulmann.cardcollection.model.CardBrand
import de.maulmann.cardcollection.model.CardManufacturer
import de.maulmann.cardcollection.model.Sport
import de.maulmann.cardcollection.model.Team
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager
// JPA Buddy will sometimes add this, ensure it's not duplicated if running locally
// import org.springframework.test.context.ActiveProfiles 

@DataJpaTest
// @ActiveProfiles("test") // Optional: If you have a specific test profile
class CardRepositoryTest {

    @Autowired
    lateinit var entityManager: TestEntityManager

    @Autowired
    lateinit var cardRepository: CardRepository

    @Test
    fun `should find cards by variantId`() {
        // Setup Variants
        val variant1 = Variant(name = "Gold Prizm")
        val variant2 = Variant(name = "Silver Holo")
        // The id for variant will be generated by the database, so we don't set it here.
        // entityManager.persist() will assign the generated id to the object.
        entityManager.persist(variant1)
        entityManager.persist(variant2)

        // Setup other necessary entities like Player, Team, Sport, Manufacturer, Brand, Theme
        val sport = Sport(name = "Basketball")
        entityManager.persist(sport)
        val team = Team(name = "Any Team", sport = sport)
        entityManager.persist(team)
        // Player needs sport and team.
        val player = Player(name = "John", surname = "Doe", team = team, sport = sport)
        entityManager.persist(player)
        
        val manufacturer = CardManufacturer(name = "Panini")
        entityManager.persist(manufacturer)
        // CardBrand needs manufacturer.
        val brand = CardBrand(name = "Prizm", manufacturer = manufacturer)
        entityManager.persist(brand)
        // CardTheme needs brand.
        val theme = CardTheme(name = "Base Set", brand = brand)
        entityManager.persist(theme)
        
        // Setup Cards
        // Card needs player, theme, and variant. All are non-nullable.
        val card1 = Card(player = player, theme = theme, variant = variant1, printRun = 10, serialNumber = 1, season = "2023", number = "1", rookieCard = false, gameUsedMaterial = false, autograph = false)
        val card2 = Card(player = player, theme = theme, variant = variant2, printRun = 25, serialNumber = 2, season = "2023", number = "2", rookieCard = true, gameUsedMaterial = false, autograph = false)
        val card3 = Card(player = player, theme = theme, variant = variant1, printRun = 5, serialNumber = 3, season = "2023", number = "3", rookieCard = false, gameUsedMaterial = true, autograph = false)
        entityManager.persist(card1)
        entityManager.persist(card2)
        entityManager.persist(card3)
        entityManager.flush() // Ensure all persist operations are sent to the database

        // Test findAllByVariantId - variant1.id should be populated after persist
        val foundCards = cardRepository.findAllByVariantId(variant1.id!!) // Using !! because id is nullable but should be set by persist

        // Assertions
        assertThat(foundCards).hasSize(2)
        // Check that only cards with variant1 are found
        assertThat(foundCards).containsExactlyInAnyOrder(card1, card3)
        assertThat(foundCards).allMatch { it.variant.id == variant1.id }
    }

    @Test
    fun `should return empty list when no cards match variantId`() {
        // Ensure some variants and cards exist to make the test meaningful,
        // but none that will match the nonExistentVariantId.
        val sport = Sport(name = "Soccer")
        entityManager.persist(sport)
        val team = Team(name = "Another Team", sport = sport)
        entityManager.persist(team)
        val player = Player(name = "Jane", surname = "Doe", team = team, sport = sport)
        entityManager.persist(player)
        val manufacturer = CardManufacturer(name = "Topps")
        entityManager.persist(manufacturer)
        val brand = CardBrand(name = "Chrome", manufacturer = manufacturer)
        entityManager.persist(brand)
        val theme = CardTheme(name = "Champions League", brand = brand)
        entityManager.persist(theme)
        val variantExisting = Variant(name = "Refractor")
        entityManager.persist(variantExisting)

        val cardExisting = Card(player = player, theme = theme, variant = variantExisting, printRun = 100, serialNumber = 10, season = "2024", number = "100", rookieCard = false, gameUsedMaterial = false, autograph = false)
        entityManager.persist(cardExisting)
        entityManager.flush()

        val nonExistentVariantId = 999L // An ID that is unlikely to exist
        val foundCards = cardRepository.findAllByVariantId(nonExistentVariantId)
        assertThat(foundCards).isEmpty()
    }

    @Test
    fun `should return empty list if variantId exists but no cards are associated`() {
        // Setup a variant that will have no cards associated with it for this test
        val variantWithNoCards = Variant(name = "Unused Variant")
        entityManager.persist(variantWithNoCards)
        entityManager.flush()

        // Ensure other cards and variants exist to make the test meaningful
        val sport = Sport(name = "Baseball")
        entityManager.persist(sport)
        val team = Team(name = "Yet Another Team", sport = sport)
        entityManager.persist(team)
        val player = Player(name = "Jim", surname = "Beam", team = team, sport = sport)
        entityManager.persist(player)
        val manufacturer = CardManufacturer(name = "Upper Deck")
        entityManager.persist(manufacturer)
        val brand = CardBrand(name = "Artifacts", manufacturer = manufacturer)
        entityManager.persist(brand)
        val theme = CardTheme(name = "Rookie Update", brand = brand)
        entityManager.persist(theme)
        val otherVariant = Variant(name = "Red Parallel")
        entityManager.persist(otherVariant)
        val cardWithOtherVariant = Card(player = player, theme = theme, variant = otherVariant, printRun = 50, serialNumber = 5, season = "2022", number = "50", rookieCard = true, gameUsedMaterial = false, autograph = true)
        entityManager.persist(cardWithOtherVariant)
        entityManager.flush()

        val foundCards = cardRepository.findAllByVariantId(variantWithNoCards.id!!)
        assertThat(foundCards).isEmpty()
    }

    // Helper function to set up common entities to avoid repetition
    private fun setupCommonEntities(): Triple<Player, CardTheme, Variant> {
        val sport = Sport(name = "TestSportCommon"); entityManager.persist(sport)
        val team = Team(name = "TestTeamCommon", sport = sport); entityManager.persist(team)
        val player = Player(name = "TestPlayerCommon", surname = "TestSurnameCommon", team = team, sport = sport); entityManager.persist(player)
        val manufacturer = CardManufacturer(name = "TestManuCommon"); entityManager.persist(manufacturer)
        val brand = CardBrand(name = "TestBrandCommon", manufacturer = manufacturer); entityManager.persist(brand)
        val theme = CardTheme(name = "TestThemeCommon", brand = brand); entityManager.persist(theme)
        val variant = Variant(name = "TestVariantCommon"); entityManager.persist(variant)
        entityManager.flush()
        return Triple(player, theme, variant)
    }

    @Test
    fun `should find cards by exact printRun`() {
        val (player, theme, variant) = setupCommonEntities()

        val cardPR1 = Card(player = player, theme = theme, variant = variant, printRun = 1, serialNumber = 1, season = "S1", number = "N1")
        val cardPR10 = Card(player = player, theme = theme, variant = variant, printRun = 10, serialNumber = 2, season = "S2", number = "N2")
        val cardPR50 = Card(player = player, theme = theme, variant = variant, printRun = 50, serialNumber = 3, season = "S3", number = "N3")
        val anotherCardPR1 = Card(player = player, theme = theme, variant = variant, printRun = 1, serialNumber = 4, season = "S4", number = "N4")

        entityManager.persist(cardPR1)
        entityManager.persist(cardPR10)
        entityManager.persist(cardPR50)
        entityManager.persist(anotherCardPR1)
        entityManager.flush()

        // Test for printRun = 1
        var foundCards = cardRepository.findAllByPrintRun(1)
        assertThat(foundCards).hasSize(2)
        assertThat(foundCards).containsExactlyInAnyOrder(cardPR1, anotherCardPR1)
        assertThat(foundCards).allMatch { it.printRun == 1 }

        // Test for printRun = 10
        foundCards = cardRepository.findAllByPrintRun(10)
        assertThat(foundCards).hasSize(1)
        assertThat(foundCards).containsExactly(cardPR10)
        assertThat(foundCards.first().printRun).isEqualTo(10)
        
        // Test for a print run that doesn't exist
        foundCards = cardRepository.findAllByPrintRun(999)
        assertThat(foundCards).isEmpty()
        
        // Test for printRun = 0 (assuming printRun is non-negative, and 0 means not specified or very rare)
        // If 0 is a valid print run value you want to test, ensure some cards have printRun = 0
        val cardPR0 = Card(player = player, theme = theme, variant = variant, printRun = 0, serialNumber = 5, season = "S5", number = "N5")
        entityManager.persist(cardPR0)
        entityManager.flush()
        foundCards = cardRepository.findAllByPrintRun(0)
        assertThat(foundCards).hasSize(1)
        assertThat(foundCards).containsExactly(cardPR0)

    }

    @Test
    fun `should find cards by printRunGreaterThan`() {
        val (player, theme, variant) = setupCommonEntities()

        // Using slightly different print runs for this test
        val cardPR1_gt = Card(player = player, theme = theme, variant = variant, printRun = 1, serialNumber = 11, season = "S11", number = "N11")
        val cardPR10_gt = Card(player = player, theme = theme, variant = variant, printRun = 10, serialNumber = 12, season = "S12", number = "N12")
        val cardPR50_gt = Card(player = player, theme = theme, variant = variant, printRun = 50, serialNumber = 13, season = "S13", number = "N13")
        val cardPR0_gt = Card(player = player, theme = theme, variant = variant, printRun = 0, serialNumber = 14, season = "S14", number = "N14") // Card with printRun = 0

        entityManager.persist(cardPR1_gt)
        entityManager.persist(cardPR10_gt)
        entityManager.persist(cardPR50_gt)
        entityManager.persist(cardPR0_gt)
        entityManager.flush()

        // Test for printRun > 0
        // This should exclude cardPR0_gt
        var foundCards = cardRepository.findAllByPrintRunGreaterThan(0)
        assertThat(foundCards).hasSize(3)
        assertThat(foundCards).containsExactlyInAnyOrder(cardPR1_gt, cardPR10_gt, cardPR50_gt)
        assertThat(foundCards).allMatch { it.printRun > 0 }

        // Test for printRun > 10
        // This should include cardPR50_gt
        foundCards = cardRepository.findAllByPrintRunGreaterThan(10)
        assertThat(foundCards).hasSize(1)
        assertThat(foundCards).containsExactly(cardPR50_gt)
        assertThat(foundCards.first().printRun).isEqualTo(50)

        // Test for printRun > 50 (greater than any existing print run)
        foundCards = cardRepository.findAllByPrintRunGreaterThan(50)
        assertThat(foundCards).isEmpty()
        
        // Test for printRun > 100 (also greater than any existing)
        foundCards = cardRepository.findAllByPrintRunGreaterThan(100)
        assertThat(foundCards).isEmpty()
    }
}
