package de.maulmann.cardcollection.repository

import de.maulmann.cardcollection.model.Card
import de.maulmann.cardcollection.model.Player
import de.maulmann.cardcollection.model.Variant
import de.maulmann.cardcollection.model.CardTheme
import de.maulmann.cardcollection.model.CardBrand
import de.maulmann.cardcollection.model.CardManufacturer
import de.maulmann.cardcollection.model.Sport
import de.maulmann.cardcollection.model.Team
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager
// JPA Buddy will sometimes add this, ensure it's not duplicated if running locally
// import org.springframework.test.context.ActiveProfiles 

@DataJpaTest
// @ActiveProfiles("test") // Optional: If you have a specific test profile
class CardRepositoryTest {

    @Autowired
    lateinit var entityManager: TestEntityManager

    @Autowired
    lateinit var cardRepository: CardRepository

    @Test
    fun `should find cards by variantId`() {
        // Setup Variants
        val variant1 = Variant(name = "Gold Prizm")
        val variant2 = Variant(name = "Silver Holo")
        // The id for variant will be generated by the database, so we don't set it here.
        // entityManager.persist() will assign the generated id to the object.
        entityManager.persist(variant1)
        entityManager.persist(variant2)

        // Setup other necessary entities like Player, Team, Sport, Manufacturer, Brand, Theme
        val sport = Sport(name = "Basketball")
        entityManager.persist(sport)
        val team = Team(name = "Any Team", sport = sport)
        entityManager.persist(team)
        // Player needs sport and team.
        val player = Player(name = "John", surname = "Doe", team = team, sport = sport)
        entityManager.persist(player)
        
        val manufacturer = CardManufacturer(name = "Panini")
        entityManager.persist(manufacturer)
        // CardBrand needs manufacturer.
        val brand = CardBrand(name = "Prizm", manufacturer = manufacturer)
        entityManager.persist(brand)
        // CardTheme needs brand.
        val theme = CardTheme(name = "Base Set", brand = brand)
        entityManager.persist(theme)
        
        // Setup Cards
        // Card needs player, theme, and variant. All are non-nullable.
        val card1 = Card(player = player, theme = theme, variant = variant1, printRun = 10, serialNumber = 1, season = "2023", number = "1", rookieCard = false, gameUsedMaterial = false, autograph = false)
        val card2 = Card(player = player, theme = theme, variant = variant2, printRun = 25, serialNumber = 2, season = "2023", number = "2", rookieCard = true, gameUsedMaterial = false, autograph = false)
        val card3 = Card(player = player, theme = theme, variant = variant1, printRun = 5, serialNumber = 3, season = "2023", number = "3", rookieCard = false, gameUsedMaterial = true, autograph = false)
        entityManager.persist(card1)
        entityManager.persist(card2)
        entityManager.persist(card3)
        entityManager.flush() // Ensure all persist operations are sent to the database

        // Test findAllByVariantId - variant1.id should be populated after persist
        val foundCards = cardRepository.findAllByVariantId(variant1.id!!) // Using !! because id is nullable but should be set by persist

        // Assertions
        assertThat(foundCards).hasSize(2)
        // Check that only cards with variant1 are found
        assertThat(foundCards).containsExactlyInAnyOrder(card1, card3)
        assertThat(foundCards).allMatch { it.variant.id == variant1.id }
    }

    @Test
    fun `should return empty list when no cards match variantId`() {
        // Ensure some variants and cards exist to make the test meaningful,
        // but none that will match the nonExistentVariantId.
        val sport = Sport(name = "Soccer")
        entityManager.persist(sport)
        val team = Team(name = "Another Team", sport = sport)
        entityManager.persist(team)
        val player = Player(name = "Jane", surname = "Doe", team = team, sport = sport)
        entityManager.persist(player)
        val manufacturer = CardManufacturer(name = "Topps")
        entityManager.persist(manufacturer)
        val brand = CardBrand(name = "Chrome", manufacturer = manufacturer)
        entityManager.persist(brand)
        val theme = CardTheme(name = "Champions League", brand = brand)
        entityManager.persist(theme)
        val variantExisting = Variant(name = "Refractor")
        entityManager.persist(variantExisting)

        val cardExisting = Card(player = player, theme = theme, variant = variantExisting, printRun = 100, serialNumber = 10, season = "2024", number = "100", rookieCard = false, gameUsedMaterial = false, autograph = false)
        entityManager.persist(cardExisting)
        entityManager.flush()

        val nonExistentVariantId = 999L // An ID that is unlikely to exist
        val foundCards = cardRepository.findAllByVariantId(nonExistentVariantId)
        assertThat(foundCards).isEmpty()
    }

    @Test
    fun `should return empty list if variantId exists but no cards are associated`() {
        // Setup a variant that will have no cards associated with it for this test
        val variantWithNoCards = Variant(name = "Unused Variant")
        entityManager.persist(variantWithNoCards)
        entityManager.flush()

        // Ensure other cards and variants exist to make the test meaningful
        val sport = Sport(name = "Baseball")
        entityManager.persist(sport)
        val team = Team(name = "Yet Another Team", sport = sport)
        entityManager.persist(team)
        val player = Player(name = "Jim", surname = "Beam", team = team, sport = sport)
        entityManager.persist(player)
        val manufacturer = CardManufacturer(name = "Upper Deck")
        entityManager.persist(manufacturer)
        val brand = CardBrand(name = "Artifacts", manufacturer = manufacturer)
        entityManager.persist(brand)
        val theme = CardTheme(name = "Rookie Update", brand = brand)
        entityManager.persist(theme)
        val otherVariant = Variant(name = "Red Parallel")
        entityManager.persist(otherVariant)
        val cardWithOtherVariant = Card(player = player, theme = theme, variant = otherVariant, printRun = 50, serialNumber = 5, season = "2022", number = "50", rookieCard = true, gameUsedMaterial = false, autograph = true)
        entityManager.persist(cardWithOtherVariant)
        entityManager.flush()

        val foundCards = cardRepository.findAllByVariantId(variantWithNoCards.id!!)
        assertThat(foundCards).isEmpty()
    }
}
